@startuml

start
: число, степень <
: результат присвоить 1]

while (степень БОЛЬШЕ 0) is (да)
if    (cтепень МОДУЛЬ 2 НЕ РАВЕН 0) then (да)
        : результат ПРИСВОИТЬ \n результат УМНОЖИТЬ число;
        : степень РАВЕН степень ВЫЧЕСТЬ 1;
endif
        : число ПРИСВОИТЬ /n число УМНОЖИТЬ число;
        : степень РАВЕН степень РАЗДЕЛИТЬ 2;
endwhile (нет)
        : результат >

end
@enduml