@startuml

start
: Число, степень<
:  ПРИСВОИТЬ 1]

while (степень БОЛЬШЕ 0) is (да)
    : счётчик ПРИСВОИТЬ \n счётчик УМНОЖИТЬ степень;
    : степень РАВНА степень ВЫЧЕСТЬ 1;
endwhile (нет)
: результат >

end

@enduml