@startuml

start

: размер ряда <
: сумма элементов ряда ]
: счётчик ПРИСВАИВАЕМ 0]

while (счётчик МЕНЬШЕ размера ряда) is (да)
    : счётчик ПРИБАВИТЬ 1;
    : сумма элементов ряда ПРИБАВИТЬ счётчик;
endwhile (нет)
    : сумма элементов ряда >

end

@enduml